<?php

declare(strict_types=1);

namespace Fabricity\Markdown\Tests\Commonmark;

class CommonMarkSpecProvider
{
    /** @return array<string, string[]> */
    public static function getCommonMarkSpec(): array
    {
        return [
            'Example 1' => ["\tfoo\tbaz\t\tbim\n", "<pre><code>foo\tbaz\t\tbim\n</code></pre>\n"],
            'Example 2' => ["  \tfoo\tbaz\t\tbim\n", "<pre><code>foo\tbaz\t\tbim\n</code></pre>\n"],
            'Example 3' => ["    a\ta\n    ὐ\ta\n", "<pre><code>a\ta\nὐ\ta\n</code></pre>\n"],
            'Example 4' => ["  - foo\n\n\tbar\n", "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n"],
            'Example 5' => ["- foo\n\n\t\tbar\n", "<ul>\n<li>\n<p>foo</p>\n<pre><code>  bar\n</code></pre>\n</li>\n</ul>\n"],
            'Example 6' => [">\t\tfoo\n", "<blockquote>\n<pre><code>  foo\n</code></pre>\n</blockquote>\n"],
            'Example 7' => ["-\t\tfoo\n", "<ul>\n<li>\n<pre><code>  foo\n</code></pre>\n</li>\n</ul>\n"],
            'Example 8' => ["    foo\n\tbar\n", "<pre><code>foo\nbar\n</code></pre>\n"],
            'Example 9' => [" - foo\n   - bar\n\t - baz\n", "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n"],
            'Example 10' => ["#\tFoo\n", "<h1>Foo</h1>\n"],
            'Example 11' => ["*\t*\t*\t\n", "<hr />\n"],
            'Example 12' => ["\\!\\\"\\#\\\$\\%\\&\\'\\(\\)\\*\\+\\,\\-\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\\\\\]\\^\\_\\`\\{\\|\\}\\~\n", "<p>!&quot;#\$%&amp;'()*+,-./:;&lt;=&gt;?@[\\]^_`{|}~</p>\n"],
            'Example 13' => ["\\\t\\A\\a\\ \\3\\φ\\«\n", "<p>\\\t\\A\\a\\ \\3\\φ\\«</p>\n"],
            'Example 14' => ["\\*not emphasized*\n\\<br/> not a tag\n\\[not a link](/foo)\n\\`not code`\n1\\. not a list\n\\* not a list\n\\# not a heading\n\\[foo]: /url \"not a reference\"\n\\&ouml; not a character entity\n", "<p>*not emphasized*\n&lt;br/&gt; not a tag\n[not a link](/foo)\n`not code`\n1. not a list\n* not a list\n# not a heading\n[foo]: /url &quot;not a reference&quot;\n&amp;ouml; not a character entity</p>\n"],
            'Example 15' => ["\\\\*emphasis*\n", "<p>\\<em>emphasis</em></p>\n"],
            'Example 16' => ["foo\\\nbar\n", "<p>foo<br />\nbar</p>\n"],
            'Example 17' => ["`` \\[\\` ``\n", "<p><code>\\[\\`</code></p>\n"],
            'Example 18' => ["    \\[\\]\n", "<pre><code>\\[\\]\n</code></pre>\n"],
            'Example 19' => ["~~~\n\\[\\]\n~~~\n", "<pre><code>\\[\\]\n</code></pre>\n"],
            'Example 20' => ["<https://example.com?find=\\*>\n", "<p><a href=\"https://example.com?find=%5C*\">https://example.com?find=\\*</a></p>\n"],
            'Example 21' => ["<a href=\"/bar\\/)\">\n", "<a href=\"/bar\\/)\">\n"],
            'Example 22' => ["[foo](/bar\\* \"ti\\*tle\")\n", "<p><a href=\"/bar*\" title=\"ti*tle\">foo</a></p>\n"],
            'Example 23' => ["[foo]\n\n[foo]: /bar\\* \"ti\\*tle\"\n", "<p><a href=\"/bar*\" title=\"ti*tle\">foo</a></p>\n"],
            'Example 24' => ["``` foo\\+bar\nfoo\n```\n", "<pre><code class=\"language-foo+bar\">foo\n</code></pre>\n"],
            'Example 25' => ["&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;\n", "<p>  &amp; © Æ Ď\n¾ ℋ ⅆ\n∲ ≧̸</p>\n"],
            'Example 26' => ["&#35; &#1234; &#992; &#0;\n", "<p># Ӓ Ϡ �</p>\n"],
            'Example 27' => ["&#X22; &#XD06; &#xcab;\n", "<p>&quot; ആ ಫ</p>\n"],
            'Example 28' => ["&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;\n", "<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n&amp;#87654321;\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>\n"],
            'Example 29' => ["&copy\n", "<p>&amp;copy</p>\n"],
            'Example 30' => ["&MadeUpEntity;\n", "<p>&amp;MadeUpEntity;</p>\n"],
            'Example 31' => ["<a href=\"&ouml;&ouml;.html\">\n", "<a href=\"&ouml;&ouml;.html\">\n"],
            'Example 32' => ["[foo](/f&ouml;&ouml; \"f&ouml;&ouml;\")\n", "<p><a href=\"/f%C3%B6%C3%B6\" title=\"föö\">foo</a></p>\n"],
            'Example 33' => ["[foo]\n\n[foo]: /f&ouml;&ouml; \"f&ouml;&ouml;\"\n", "<p><a href=\"/f%C3%B6%C3%B6\" title=\"föö\">foo</a></p>\n"],
            'Example 34' => ["``` f&ouml;&ouml;\nfoo\n```\n", "<pre><code class=\"language-föö\">foo\n</code></pre>\n"],
            'Example 35' => ["`f&ouml;&ouml;`\n", "<p><code>f&amp;ouml;&amp;ouml;</code></p>\n"],
            'Example 36' => ["    f&ouml;f&ouml;\n", "<pre><code>f&amp;ouml;f&amp;ouml;\n</code></pre>\n"],
            'Example 37' => ["&#42;foo&#42;\n*foo*\n", "<p>*foo*\n<em>foo</em></p>\n"],
            'Example 38' => ["&#42; foo\n\n* foo\n", "<p>* foo</p>\n<ul>\n<li>foo</li>\n</ul>\n"],
            'Example 39' => ["foo&#10;&#10;bar\n", "<p>foo\n\nbar</p>\n"],
            'Example 40' => ["&#9;foo\n", "<p>\tfoo</p>\n"],
            'Example 41' => ["[a](url &quot;tit&quot;)\n", "<p>[a](url &quot;tit&quot;)</p>\n"],
            'Example 42' => ["- `one\n- two`\n", "<ul>\n<li>`one</li>\n<li>two`</li>\n</ul>\n"],
            'Example 43' => ["***\n---\n___\n", "<hr />\n<hr />\n<hr />\n"],
            'Example 44' => ["+++\n", "<p>+++</p>\n"],
            'Example 45' => ["===\n", "<p>===</p>\n"],
            'Example 46' => ["--\n**\n__\n", "<p>--\n**\n__</p>\n"],
            'Example 47' => [" ***\n  ***\n   ***\n", "<hr />\n<hr />\n<hr />\n"],
            'Example 48' => ["    ***\n", "<pre><code>***\n</code></pre>\n"],
            'Example 49' => ["Foo\n    ***\n", "<p>Foo\n***</p>\n"],
            'Example 50' => ["_____________________________________\n", "<hr />\n"],
            'Example 51' => [" - - -\n", "<hr />\n"],
            'Example 52' => [" **  * ** * ** * **\n", "<hr />\n"],
            'Example 53' => ["-     -      -      -\n", "<hr />\n"],
            'Example 54' => ["- - - -    \n", "<hr />\n"],
            'Example 55' => ["_ _ _ _ a\n\na------\n\n---a---\n", "<p>_ _ _ _ a</p>\n<p>a------</p>\n<p>---a---</p>\n"],
            'Example 56' => [" *-*\n", "<p><em>-</em></p>\n"],
            'Example 57' => ["- foo\n***\n- bar\n", "<ul>\n<li>foo</li>\n</ul>\n<hr />\n<ul>\n<li>bar</li>\n</ul>\n"],
            'Example 58' => ["Foo\n***\nbar\n", "<p>Foo</p>\n<hr />\n<p>bar</p>\n"],
            'Example 59' => ["Foo\n---\nbar\n", "<h2>Foo</h2>\n<p>bar</p>\n"],
            'Example 60' => ["* Foo\n* * *\n* Bar\n", "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n<ul>\n<li>Bar</li>\n</ul>\n"],
            'Example 61' => ["- Foo\n- * * *\n", "<ul>\n<li>Foo</li>\n<li>\n<hr />\n</li>\n</ul>\n"],
            'Example 62' => ["# foo\n## foo\n### foo\n#### foo\n##### foo\n###### foo\n", "<h1>foo</h1>\n<h2>foo</h2>\n<h3>foo</h3>\n<h4>foo</h4>\n<h5>foo</h5>\n<h6>foo</h6>\n"],
            'Example 63' => ["####### foo\n", "<p>####### foo</p>\n"],
            'Example 64' => ["#5 bolt\n\n#hashtag\n", "<p>#5 bolt</p>\n<p>#hashtag</p>\n"],
            'Example 65' => ["\\## foo\n", "<p>## foo</p>\n"],
            'Example 66' => ["# foo *bar* \\*baz\\*\n", "<h1>foo <em>bar</em> *baz*</h1>\n"],
            'Example 67' => ["#                  foo                     \n", "<h1>foo</h1>\n"],
            'Example 68' => [" ### foo\n  ## foo\n   # foo\n", "<h3>foo</h3>\n<h2>foo</h2>\n<h1>foo</h1>\n"],
            'Example 69' => ["    # foo\n", "<pre><code># foo\n</code></pre>\n"],
            'Example 70' => ["foo\n    # bar\n", "<p>foo\n# bar</p>\n"],
            'Example 71' => ["## foo ##\n  ###   bar    ###\n", "<h2>foo</h2>\n<h3>bar</h3>\n"],
            'Example 72' => ["# foo ##################################\n##### foo ##\n", "<h1>foo</h1>\n<h5>foo</h5>\n"],
            'Example 73' => ["### foo ###     \n", "<h3>foo</h3>\n"],
            'Example 74' => ["### foo ### b\n", "<h3>foo ### b</h3>\n"],
            'Example 75' => ["# foo#\n", "<h1>foo#</h1>\n"],
            'Example 76' => ["### foo \\###\n## foo #\\##\n# foo \\#\n", "<h3>foo ###</h3>\n<h2>foo ###</h2>\n<h1>foo #</h1>\n"],
            'Example 77' => ["****\n## foo\n****\n", "<hr />\n<h2>foo</h2>\n<hr />\n"],
            'Example 78' => ["Foo bar\n# baz\nBar foo\n", "<p>Foo bar</p>\n<h1>baz</h1>\n<p>Bar foo</p>\n"],
            'Example 79' => ["## \n#\n### ###\n", "<h2></h2>\n<h1></h1>\n<h3></h3>\n"],
            'Example 80' => ["Foo *bar*\n=========\n\nFoo *bar*\n---------\n", "<h1>Foo <em>bar</em></h1>\n<h2>Foo <em>bar</em></h2>\n"],
            'Example 81' => ["Foo *bar\nbaz*\n====\n", "<h1>Foo <em>bar\nbaz</em></h1>\n"],
            'Example 82' => ["  Foo *bar\nbaz*\t\n====\n", "<h1>Foo <em>bar\nbaz</em></h1>\n"],
            'Example 83' => ["Foo\n-------------------------\n\nFoo\n=\n", "<h2>Foo</h2>\n<h1>Foo</h1>\n"],
            'Example 84' => ["   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===\n", "<h2>Foo</h2>\n<h2>Foo</h2>\n<h1>Foo</h1>\n"],
            'Example 85' => ["    Foo\n    ---\n\n    Foo\n---\n", "<pre><code>Foo\n---\n\nFoo\n</code></pre>\n<hr />\n"],
            'Example 86' => ["Foo\n   ----      \n", "<h2>Foo</h2>\n"],
            'Example 87' => ["Foo\n    ---\n", "<p>Foo\n---</p>\n"],
            'Example 88' => ["Foo\n= =\n\nFoo\n--- -\n", "<p>Foo\n= =</p>\n<p>Foo</p>\n<hr />\n"],
            'Example 89' => ["Foo  \n-----\n", "<h2>Foo</h2>\n"],
            'Example 90' => ["Foo\\\n----\n", "<h2>Foo\\</h2>\n"],
            'Example 91' => ["`Foo\n----\n`\n\n<a title=\"a lot\n---\nof dashes\"/>\n", "<h2>`Foo</h2>\n<p>`</p>\n<h2>&lt;a title=&quot;a lot</h2>\n<p>of dashes&quot;/&gt;</p>\n"],
            'Example 92' => ["> Foo\n---\n", "<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />\n"],
            'Example 93' => ["> foo\nbar\n===\n", "<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>\n"],
            'Example 94' => ["- Foo\n---\n", "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n"],
            'Example 95' => ["Foo\nBar\n---\n", "<h2>Foo\nBar</h2>\n"],
            'Example 96' => ["---\nFoo\n---\nBar\n---\nBaz\n", "<hr />\n<h2>Foo</h2>\n<h2>Bar</h2>\n<p>Baz</p>\n"],
            'Example 97' => ["\n====\n", "<p>====</p>\n"],
            'Example 98' => ["---\n---\n", "<hr />\n<hr />\n"],
            'Example 99' => ["- foo\n-----\n", "<ul>\n<li>foo</li>\n</ul>\n<hr />\n"],
            'Example 100' => ["    foo\n---\n", "<pre><code>foo\n</code></pre>\n<hr />\n"],
            'Example 101' => ["> foo\n-----\n", "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n"],
            'Example 102' => ["\\> foo\n------\n", "<h2>&gt; foo</h2>\n"],
            'Example 103' => ["Foo\n\nbar\n---\nbaz\n", "<p>Foo</p>\n<h2>bar</h2>\n<p>baz</p>\n"],
            'Example 104' => ["Foo\nbar\n\n---\n\nbaz\n", "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n"],
            'Example 105' => ["Foo\nbar\n* * *\nbaz\n", "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n"],
            'Example 106' => ["Foo\nbar\n\\---\nbaz\n", "<p>Foo\nbar\n---\nbaz</p>\n"],
            'Example 107' => ["    a simple\n      indented code block\n", "<pre><code>a simple\n  indented code block\n</code></pre>\n"],
            'Example 108' => ["  - foo\n\n    bar\n", "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n"],
            'Example 109' => ["1.  foo\n\n    - bar\n", "<ol>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n"],
            'Example 110' => ["    <a/>\n    *hi*\n\n    - one\n", "<pre><code>&lt;a/&gt;\n*hi*\n\n- one\n</code></pre>\n"],
            'Example 111' => ["    chunk1\n\n    chunk2\n  \n \n \n    chunk3\n", "<pre><code>chunk1\n\nchunk2\n\n\n\nchunk3\n</code></pre>\n"],
            'Example 112' => ["    chunk1\n      \n      chunk2\n", "<pre><code>chunk1\n  \n  chunk2\n</code></pre>\n"],
            'Example 113' => ["Foo\n    bar\n\n", "<p>Foo\nbar</p>\n"],
            'Example 114' => ["    foo\nbar\n", "<pre><code>foo\n</code></pre>\n<p>bar</p>\n"],
            'Example 115' => ["# Heading\n    foo\nHeading\n------\n    foo\n----\n", "<h1>Heading</h1>\n<pre><code>foo\n</code></pre>\n<h2>Heading</h2>\n<pre><code>foo\n</code></pre>\n<hr />\n"],
            'Example 116' => ["        foo\n    bar\n", "<pre><code>    foo\nbar\n</code></pre>\n"],
            'Example 117' => ["\n    \n    foo\n    \n\n", "<pre><code>foo\n</code></pre>\n"],
            'Example 118' => ["    foo  \n", "<pre><code>foo  \n</code></pre>\n"],
            'Example 119' => ["```\n<\n >\n```\n", "<pre><code>&lt;\n &gt;\n</code></pre>\n"],
            'Example 120' => ["~~~\n<\n >\n~~~\n", "<pre><code>&lt;\n &gt;\n</code></pre>\n"],
            'Example 121' => ["``\nfoo\n``\n", "<p><code>foo</code></p>\n"],
            'Example 122' => ["```\naaa\n~~~\n```\n", "<pre><code>aaa\n~~~\n</code></pre>\n"],
            'Example 123' => ["~~~\naaa\n```\n~~~\n", "<pre><code>aaa\n```\n</code></pre>\n"],
            'Example 124' => ["````\naaa\n```\n``````\n", "<pre><code>aaa\n```\n</code></pre>\n"],
            'Example 125' => ["~~~~\naaa\n~~~\n~~~~\n", "<pre><code>aaa\n~~~\n</code></pre>\n"],
            'Example 126' => ["```\n", "<pre><code></code></pre>\n"],
            'Example 127' => ["`````\n\n```\naaa\n", "<pre><code>\n```\naaa\n</code></pre>\n"],
            'Example 128' => ["> ```\n> aaa\n\nbbb\n", "<blockquote>\n<pre><code>aaa\n</code></pre>\n</blockquote>\n<p>bbb</p>\n"],
            'Example 129' => ["```\n\n  \n```\n", "<pre><code>\n  \n</code></pre>\n"],
            'Example 130' => ["```\n```\n", "<pre><code></code></pre>\n"],
            'Example 131' => [" ```\n aaa\naaa\n```\n", "<pre><code>aaa\naaa\n</code></pre>\n"],
            'Example 132' => ["  ```\naaa\n  aaa\naaa\n  ```\n", "<pre><code>aaa\naaa\naaa\n</code></pre>\n"],
            'Example 133' => ["   ```\n   aaa\n    aaa\n  aaa\n   ```\n", "<pre><code>aaa\n aaa\naaa\n</code></pre>\n"],
            'Example 134' => ["    ```\n    aaa\n    ```\n", "<pre><code>```\naaa\n```\n</code></pre>\n"],
            'Example 135' => ["```\naaa\n  ```\n", "<pre><code>aaa\n</code></pre>\n"],
            'Example 136' => ["   ```\naaa\n  ```\n", "<pre><code>aaa\n</code></pre>\n"],
            'Example 137' => ["```\naaa\n    ```\n", "<pre><code>aaa\n    ```\n</code></pre>\n"],
            'Example 138' => ["``` ```\naaa\n", "<p><code> </code>\naaa</p>\n"],
            'Example 139' => ["~~~~~~\naaa\n~~~ ~~\n", "<pre><code>aaa\n~~~ ~~\n</code></pre>\n"],
            'Example 140' => ["foo\n```\nbar\n```\nbaz\n", "<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n"],
            'Example 141' => ["foo\n---\n~~~\nbar\n~~~\n# baz\n", "<h2>foo</h2>\n<pre><code>bar\n</code></pre>\n<h1>baz</h1>\n"],
            'Example 142' => ["```ruby\ndef foo(x)\n  return 3\nend\n```\n", "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n"],
            'Example 143' => ["~~~~    ruby startline=3 \$%@#\$\ndef foo(x)\n  return 3\nend\n~~~~~~~\n", "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n"],
            'Example 144' => ["````;\n````\n", "<pre><code class=\"language-;\"></code></pre>\n"],
            'Example 145' => ["``` aa ```\nfoo\n", "<p><code>aa</code>\nfoo</p>\n"],
            'Example 146' => ["~~~ aa ``` ~~~\nfoo\n~~~\n", "<pre><code class=\"language-aa\">foo\n</code></pre>\n"],
            'Example 147' => ["```\n``` aaa\n```\n", "<pre><code>``` aaa\n</code></pre>\n"],
            'Example 148' => ["<table><tr><td>\n<pre>\n**Hello**,\n\n_world_.\n</pre>\n</td></tr></table>\n", "<table><tr><td>\n<pre>\n**Hello**,\n<p><em>world</em>.\n</pre></p>\n</td></tr></table>\n"],
            'Example 149' => ["<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n\nokay.\n", "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n<p>okay.</p>\n"],
            'Example 150' => [" <div>\n  *hello*\n         <foo><a>\n", " <div>\n  *hello*\n         <foo><a>\n"],
            'Example 151' => ["</div>\n*foo*\n", "</div>\n*foo*\n"],
            'Example 152' => ["<DIV CLASS=\"foo\">\n\n*Markdown*\n\n</DIV>\n", "<DIV CLASS=\"foo\">\n<p><em>Markdown</em></p>\n</DIV>\n"],
            'Example 153' => ["<div id=\"foo\"\n  class=\"bar\">\n</div>\n", "<div id=\"foo\"\n  class=\"bar\">\n</div>\n"],
            'Example 154' => ["<div id=\"foo\" class=\"bar\n  baz\">\n</div>\n", "<div id=\"foo\" class=\"bar\n  baz\">\n</div>\n"],
            'Example 155' => ["<div>\n*foo*\n\n*bar*\n", "<div>\n*foo*\n<p><em>bar</em></p>\n"],
            'Example 156' => ["<div id=\"foo\"\n*hi*\n", "<div id=\"foo\"\n*hi*\n"],
            'Example 157' => ["<div class\nfoo\n", "<div class\nfoo\n"],
            'Example 158' => ["<div *???-&&&-<---\n*foo*\n", "<div *???-&&&-<---\n*foo*\n"],
            'Example 159' => ["<div><a href=\"bar\">*foo*</a></div>\n", "<div><a href=\"bar\">*foo*</a></div>\n"],
            'Example 160' => ["<table><tr><td>\nfoo\n</td></tr></table>\n", "<table><tr><td>\nfoo\n</td></tr></table>\n"],
            'Example 161' => ["<div></div>\n``` c\nint x = 33;\n```\n", "<div></div>\n``` c\nint x = 33;\n```\n"],
            'Example 162' => ["<a href=\"foo\">\n*bar*\n</a>\n", "<a href=\"foo\">\n*bar*\n</a>\n"],
            'Example 163' => ["<Warning>\n*bar*\n</Warning>\n", "<Warning>\n*bar*\n</Warning>\n"],
            'Example 164' => ["<i class=\"foo\">\n*bar*\n</i>\n", "<i class=\"foo\">\n*bar*\n</i>\n"],
            'Example 165' => ["</ins>\n*bar*\n", "</ins>\n*bar*\n"],
            'Example 166' => ["<del>\n*foo*\n</del>\n", "<del>\n*foo*\n</del>\n"],
            'Example 167' => ["<del>\n\n*foo*\n\n</del>\n", "<del>\n<p><em>foo</em></p>\n</del>\n"],
            'Example 168' => ["<del>*foo*</del>\n", "<p><del><em>foo</em></del></p>\n"],
            'Example 169' => ["<pre language=\"haskell\"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print \$ parseTags tags\n</code></pre>\nokay\n", "<pre language=\"haskell\"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print \$ parseTags tags\n</code></pre>\n<p>okay</p>\n"],
            'Example 170' => ["<script type=\"text/javascript\">\n// JavaScript example\n\ndocument.getElementById(\"demo\").innerHTML = \"Hello JavaScript!\";\n</script>\nokay\n", "<script type=\"text/javascript\">\n// JavaScript example\n\ndocument.getElementById(\"demo\").innerHTML = \"Hello JavaScript!\";\n</script>\n<p>okay</p>\n"],
            'Example 171' => ["<textarea>\n\n*foo*\n\n_bar_\n\n</textarea>\n", "<textarea>\n\n*foo*\n\n_bar_\n\n</textarea>\n"],
            'Example 172' => ["<style\n  type=\"text/css\">\nh1 {color:red;}\n\np {color:blue;}\n</style>\nokay\n", "<style\n  type=\"text/css\">\nh1 {color:red;}\n\np {color:blue;}\n</style>\n<p>okay</p>\n"],
            'Example 173' => ["<style\n  type=\"text/css\">\n\nfoo\n", "<style\n  type=\"text/css\">\n\nfoo\n"],
            'Example 174' => ["> <div>\n> foo\n\nbar\n", "<blockquote>\n<div>\nfoo\n</blockquote>\n<p>bar</p>\n"],
            'Example 175' => ["- <div>\n- foo\n", "<ul>\n<li>\n<div>\n</li>\n<li>foo</li>\n</ul>\n"],
            'Example 176' => ["<style>p{color:red;}</style>\n*foo*\n", "<style>p{color:red;}</style>\n<p><em>foo</em></p>\n"],
            'Example 177' => ["<!-- foo -->*bar*\n*baz*\n", "<!-- foo -->*bar*\n<p><em>baz</em></p>\n"],
            'Example 178' => ["<script>\nfoo\n</script>1. *bar*\n", "<script>\nfoo\n</script>1. *bar*\n"],
            'Example 179' => ["<!-- Foo\n\nbar\n   baz -->\nokay\n", "<!-- Foo\n\nbar\n   baz -->\n<p>okay</p>\n"],
            'Example 180' => ["<?php\n\n  echo '>';\n\n?>\nokay\n", "<?php\n\n  echo '>';\n\n?>\n<p>okay</p>\n"],
            'Example 181' => ["<!DOCTYPE html>\n", "<!DOCTYPE html>\n"],
            'Example 182' => ["<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\nokay\n", "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\n<p>okay</p>\n"],
            'Example 183' => ["  <!-- foo -->\n\n    <!-- foo -->\n", "  <!-- foo -->\n<pre><code>&lt;!-- foo --&gt;\n</code></pre>\n"],
            'Example 184' => ["  <div>\n\n    <div>\n", "  <div>\n<pre><code>&lt;div&gt;\n</code></pre>\n"],
            'Example 185' => ["Foo\n<div>\nbar\n</div>\n", "<p>Foo</p>\n<div>\nbar\n</div>\n"],
            'Example 186' => ["<div>\nbar\n</div>\n*foo*\n", "<div>\nbar\n</div>\n*foo*\n"],
            'Example 187' => ["Foo\n<a href=\"bar\">\nbaz\n", "<p>Foo\n<a href=\"bar\">\nbaz</p>\n"],
            'Example 188' => ["<div>\n\n*Emphasized* text.\n\n</div>\n", "<div>\n<p><em>Emphasized</em> text.</p>\n</div>\n"],
            'Example 189' => ["<div>\n*Emphasized* text.\n</div>\n", "<div>\n*Emphasized* text.\n</div>\n"],
            'Example 190' => ["<table>\n\n<tr>\n\n<td>\nHi\n</td>\n\n</tr>\n\n</table>\n", "<table>\n<tr>\n<td>\nHi\n</td>\n</tr>\n</table>\n"],
            'Example 191' => ["<table>\n\n  <tr>\n\n    <td>\n      Hi\n    </td>\n\n  </tr>\n\n</table>\n", "<table>\n  <tr>\n<pre><code>&lt;td&gt;\n  Hi\n&lt;/td&gt;\n</code></pre>\n  </tr>\n</table>\n"],
            'Example 192' => ["[foo]: /url \"title\"\n\n[foo]\n", "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"],
            'Example 193' => ["   [foo]: \n      /url  \n           'the title'  \n\n[foo]\n", "<p><a href=\"/url\" title=\"the title\">foo</a></p>\n"],
            'Example 194' => ["[Foo*bar\\]]:my_(url) 'title (with parens)'\n\n[Foo*bar\\]]\n", "<p><a href=\"my_(url)\" title=\"title (with parens)\">Foo*bar]</a></p>\n"],
            'Example 195' => ["[Foo bar]:\n<my url>\n'title'\n\n[Foo bar]\n", "<p><a href=\"my%20url\" title=\"title\">Foo bar</a></p>\n"],
            'Example 196' => ["[foo]: /url '\ntitle\nline1\nline2\n'\n\n[foo]\n", "<p><a href=\"/url\" title=\"\ntitle\nline1\nline2\n\">foo</a></p>\n"],
            'Example 197' => ["[foo]: /url 'title\n\nwith blank line'\n\n[foo]\n", "<p>[foo]: /url 'title</p>\n<p>with blank line'</p>\n<p>[foo]</p>\n"],
            'Example 198' => ["[foo]:\n/url\n\n[foo]\n", "<p><a href=\"/url\">foo</a></p>\n"],
            'Example 199' => ["[foo]:\n\n[foo]\n", "<p>[foo]:</p>\n<p>[foo]</p>\n"],
            'Example 200' => ["[foo]: <>\n\n[foo]\n", "<p><a href=\"\">foo</a></p>\n"],
            'Example 201' => ["[foo]: <bar>(baz)\n\n[foo]\n", "<p>[foo]: <bar>(baz)</p>\n<p>[foo]</p>\n"],
            'Example 202' => ["[foo]: /url\\bar\\*baz \"foo\\\"bar\\baz\"\n\n[foo]\n", "<p><a href=\"/url%5Cbar*baz\" title=\"foo&quot;bar\\baz\">foo</a></p>\n"],
            'Example 203' => ["[foo]\n\n[foo]: url\n", "<p><a href=\"url\">foo</a></p>\n"],
            'Example 204' => ["[foo]\n\n[foo]: first\n[foo]: second\n", "<p><a href=\"first\">foo</a></p>\n"],
            'Example 205' => ["[FOO]: /url\n\n[Foo]\n", "<p><a href=\"/url\">Foo</a></p>\n"],
            'Example 206' => ["[ΑΓΩ]: /φου\n\n[αγω]\n", "<p><a href=\"/%CF%86%CE%BF%CF%85\">αγω</a></p>\n"],
            'Example 207' => ["[foo]: /url\n", ''],
            'Example 208' => ["[\nfoo\n]: /url\nbar\n", "<p>bar</p>\n"],
            'Example 209' => ["[foo]: /url \"title\" ok\n", "<p>[foo]: /url &quot;title&quot; ok</p>\n"],
            'Example 210' => ["[foo]: /url\n\"title\" ok\n", "<p>&quot;title&quot; ok</p>\n"],
            'Example 211' => ["    [foo]: /url \"title\"\n\n[foo]\n", "<pre><code>[foo]: /url &quot;title&quot;\n</code></pre>\n<p>[foo]</p>\n"],
            'Example 212' => ["```\n[foo]: /url\n```\n\n[foo]\n", "<pre><code>[foo]: /url\n</code></pre>\n<p>[foo]</p>\n"],
            'Example 213' => ["Foo\n[bar]: /baz\n\n[bar]\n", "<p>Foo\n[bar]: /baz</p>\n<p>[bar]</p>\n"],
            'Example 214' => ["# [Foo]\n[foo]: /url\n> bar\n", "<h1><a href=\"/url\">Foo</a></h1>\n<blockquote>\n<p>bar</p>\n</blockquote>\n"],
            'Example 215' => ["[foo]: /url\nbar\n===\n[foo]\n", "<h1>bar</h1>\n<p><a href=\"/url\">foo</a></p>\n"],
            'Example 216' => ["[foo]: /url\n===\n[foo]\n", "<p>===\n<a href=\"/url\">foo</a></p>\n"],
            'Example 217' => ["[foo]: /foo-url \"foo\"\n[bar]: /bar-url\n  \"bar\"\n[baz]: /baz-url\n\n[foo],\n[bar],\n[baz]\n", "<p><a href=\"/foo-url\" title=\"foo\">foo</a>,\n<a href=\"/bar-url\" title=\"bar\">bar</a>,\n<a href=\"/baz-url\">baz</a></p>\n"],
            'Example 218' => ["[foo]\n\n> [foo]: /url\n", "<p><a href=\"/url\">foo</a></p>\n<blockquote>\n</blockquote>\n"],
            'Example 219' => ["aaa\n\nbbb\n", "<p>aaa</p>\n<p>bbb</p>\n"],
            'Example 220' => ["aaa\nbbb\n\nccc\nddd\n", "<p>aaa\nbbb</p>\n<p>ccc\nddd</p>\n"],
            'Example 221' => ["aaa\n\n\nbbb\n", "<p>aaa</p>\n<p>bbb</p>\n"],
            'Example 222' => ["  aaa\n bbb\n", "<p>aaa\nbbb</p>\n"],
            'Example 223' => ["aaa\n             bbb\n                                       ccc\n", "<p>aaa\nbbb\nccc</p>\n"],
            'Example 224' => ["   aaa\nbbb\n", "<p>aaa\nbbb</p>\n"],
            'Example 225' => ["    aaa\nbbb\n", "<pre><code>aaa\n</code></pre>\n<p>bbb</p>\n"],
            'Example 226' => ["aaa     \nbbb     \n", "<p>aaa<br />\nbbb</p>\n"],
            'Example 227' => ["  \n\naaa\n  \n\n# aaa\n\n  \n", "<p>aaa</p>\n<h1>aaa</h1>\n"],
            'Example 228' => ["> # Foo\n> bar\n> baz\n", "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n"],
            'Example 229' => ["># Foo\n>bar\n> baz\n", "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n"],
            'Example 230' => ["   > # Foo\n   > bar\n > baz\n", "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n"],
            'Example 231' => ["    > # Foo\n    > bar\n    > baz\n", "<pre><code>&gt; # Foo\n&gt; bar\n&gt; baz\n</code></pre>\n"],
            'Example 232' => ["> # Foo\n> bar\nbaz\n", "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n"],
            'Example 233' => ["> bar\nbaz\n> foo\n", "<blockquote>\n<p>bar\nbaz\nfoo</p>\n</blockquote>\n"],
            'Example 234' => ["> foo\n---\n", "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n"],
            'Example 235' => ["> - foo\n- bar\n", "<blockquote>\n<ul>\n<li>foo</li>\n</ul>\n</blockquote>\n<ul>\n<li>bar</li>\n</ul>\n"],
            'Example 236' => [">     foo\n    bar\n", "<blockquote>\n<pre><code>foo\n</code></pre>\n</blockquote>\n<pre><code>bar\n</code></pre>\n"],
            'Example 237' => ["> ```\nfoo\n```\n", "<blockquote>\n<pre><code></code></pre>\n</blockquote>\n<p>foo</p>\n<pre><code></code></pre>\n"],
            'Example 238' => ["> foo\n    - bar\n", "<blockquote>\n<p>foo\n- bar</p>\n</blockquote>\n"],
            'Example 239' => [">\n", "<blockquote>\n</blockquote>\n"],
            'Example 240' => [">\n>  \n> \n", "<blockquote>\n</blockquote>\n"],
            'Example 241' => [">\n> foo\n>  \n", "<blockquote>\n<p>foo</p>\n</blockquote>\n"],
            'Example 242' => ["> foo\n\n> bar\n", "<blockquote>\n<p>foo</p>\n</blockquote>\n<blockquote>\n<p>bar</p>\n</blockquote>\n"],
            'Example 243' => ["> foo\n> bar\n", "<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n"],
            'Example 244' => ["> foo\n>\n> bar\n", "<blockquote>\n<p>foo</p>\n<p>bar</p>\n</blockquote>\n"],
            'Example 245' => ["foo\n> bar\n", "<p>foo</p>\n<blockquote>\n<p>bar</p>\n</blockquote>\n"],
            'Example 246' => ["> aaa\n***\n> bbb\n", "<blockquote>\n<p>aaa</p>\n</blockquote>\n<hr />\n<blockquote>\n<p>bbb</p>\n</blockquote>\n"],
            'Example 247' => ["> bar\nbaz\n", "<blockquote>\n<p>bar\nbaz</p>\n</blockquote>\n"],
            'Example 248' => ["> bar\n\nbaz\n", "<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n"],
            'Example 249' => ["> bar\n>\nbaz\n", "<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n"],
            'Example 250' => ["> > > foo\nbar\n", "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n</blockquote>\n</blockquote>\n"],
            'Example 251' => [">>> foo\n> bar\n>>baz\n", "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar\nbaz</p>\n</blockquote>\n</blockquote>\n</blockquote>\n"],
            'Example 252' => [">     code\n\n>    not code\n", "<blockquote>\n<pre><code>code\n</code></pre>\n</blockquote>\n<blockquote>\n<p>not code</p>\n</blockquote>\n"],
            'Example 253' => ["A paragraph\nwith two lines.\n\n    indented code\n\n> A block quote.\n", "<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n"],
            'Example 254' => ["1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.\n", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n"],
            'Example 255' => ["- one\n\n two\n", "<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n"],
            'Example 256' => ["- one\n\n  two\n", "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n"],
            'Example 257' => [" -    one\n\n     two\n", "<ul>\n<li>one</li>\n</ul>\n<pre><code> two\n</code></pre>\n"],
            'Example 258' => [" -    one\n\n      two\n", "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n"],
            'Example 259' => ["   > > 1.  one\n>>\n>>     two\n", "<blockquote>\n<blockquote>\n<ol>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ol>\n</blockquote>\n</blockquote>\n"],
            'Example 260' => [">>- one\n>>\n  >  > two\n", "<blockquote>\n<blockquote>\n<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n</blockquote>\n</blockquote>\n"],
            'Example 261' => ["-one\n\n2.two\n", "<p>-one</p>\n<p>2.two</p>\n"],
            'Example 262' => ["- foo\n\n\n  bar\n", "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n"],
            'Example 263' => ["1.  foo\n\n    ```\n    bar\n    ```\n\n    baz\n\n    > bam\n", "<ol>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n<blockquote>\n<p>bam</p>\n</blockquote>\n</li>\n</ol>\n"],
            'Example 264' => ["- Foo\n\n      bar\n\n\n      baz\n", "<ul>\n<li>\n<p>Foo</p>\n<pre><code>bar\n\n\nbaz\n</code></pre>\n</li>\n</ul>\n"],
            'Example 265' => ["123456789. ok\n", "<ol start=\"123456789\">\n<li>ok</li>\n</ol>\n"],
            'Example 266' => ["1234567890. not ok\n", "<p>1234567890. not ok</p>\n"],
            'Example 267' => ["0. ok\n", "<ol start=\"0\">\n<li>ok</li>\n</ol>\n"],
            'Example 268' => ["003. ok\n", "<ol start=\"3\">\n<li>ok</li>\n</ol>\n"],
            'Example 269' => ["-1. not ok\n", "<p>-1. not ok</p>\n"],
            'Example 270' => ["- foo\n\n      bar\n", "<ul>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ul>\n"],
            'Example 271' => ["  10.  foo\n\n           bar\n", "<ol start=\"10\">\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ol>\n"],
            'Example 272' => ["    indented code\n\nparagraph\n\n    more code\n", "<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n"],
            'Example 273' => ["1.     indented code\n\n   paragraph\n\n       more code\n", "<ol>\n<li>\n<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n"],
            'Example 274' => ["1.      indented code\n\n   paragraph\n\n       more code\n", "<ol>\n<li>\n<pre><code> indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n"],
            'Example 275' => ["   foo\n\nbar\n", "<p>foo</p>\n<p>bar</p>\n"],
            'Example 276' => ["-    foo\n\n  bar\n", "<ul>\n<li>foo</li>\n</ul>\n<p>bar</p>\n"],
            'Example 277' => ["-  foo\n\n   bar\n", "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n"],
            'Example 278' => ["-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz\n", "<ul>\n<li>foo</li>\n<li>\n<pre><code>bar\n</code></pre>\n</li>\n<li>\n<pre><code>baz\n</code></pre>\n</li>\n</ul>\n"],
            'Example 279' => ["-   \n  foo\n", "<ul>\n<li>foo</li>\n</ul>\n"],
            'Example 280' => ["-\n\n  foo\n", "<ul>\n<li></li>\n</ul>\n<p>foo</p>\n"],
            'Example 281' => ["- foo\n-\n- bar\n", "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n"],
            'Example 282' => ["- foo\n-   \n- bar\n", "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n"],
            'Example 283' => ["1. foo\n2.\n3. bar\n", "<ol>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ol>\n"],
            'Example 284' => ["*\n", "<ul>\n<li></li>\n</ul>\n"],
            'Example 285' => ["foo\n*\n\nfoo\n1.\n", "<p>foo\n*</p>\n<p>foo\n1.</p>\n"],
            'Example 286' => [" 1.  A paragraph\n     with two lines.\n\n         indented code\n\n     > A block quote.\n", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n"],
            'Example 287' => ["  1.  A paragraph\n      with two lines.\n\n          indented code\n\n      > A block quote.\n", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n"],
            'Example 288' => ["   1.  A paragraph\n       with two lines.\n\n           indented code\n\n       > A block quote.\n", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n"],
            'Example 289' => ["    1.  A paragraph\n        with two lines.\n\n            indented code\n\n        > A block quote.\n", "<pre><code>1.  A paragraph\n    with two lines.\n\n        indented code\n\n    &gt; A block quote.\n</code></pre>\n"],
            'Example 290' => ["  1.  A paragraph\nwith two lines.\n\n          indented code\n\n      > A block quote.\n", "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n"],
            'Example 291' => ["  1.  A paragraph\n    with two lines.\n", "<ol>\n<li>A paragraph\nwith two lines.</li>\n</ol>\n"],
            'Example 292' => ["> 1. > Blockquote\ncontinued here.\n", "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n"],
            'Example 293' => ["> 1. > Blockquote\n> continued here.\n", "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n"],
            'Example 294' => ["- foo\n  - bar\n    - baz\n      - boo\n", "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz\n<ul>\n<li>boo</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n"],
            'Example 295' => ["- foo\n - bar\n  - baz\n   - boo\n", "<ul>\n<li>foo</li>\n<li>bar</li>\n<li>baz</li>\n<li>boo</li>\n</ul>\n"],
            'Example 296' => ["10) foo\n    - bar\n", "<ol start=\"10\">\n<li>foo\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n"],
            'Example 297' => ["10) foo\n   - bar\n", "<ol start=\"10\">\n<li>foo</li>\n</ol>\n<ul>\n<li>bar</li>\n</ul>\n"],
            'Example 298' => ["- - foo\n", "<ul>\n<li>\n<ul>\n<li>foo</li>\n</ul>\n</li>\n</ul>\n"],
            'Example 299' => ["1. - 2. foo\n", "<ol>\n<li>\n<ul>\n<li>\n<ol start=\"2\">\n<li>foo</li>\n</ol>\n</li>\n</ul>\n</li>\n</ol>\n"],
            'Example 300' => ["- # Foo\n- Bar\n  ---\n  baz\n", "<ul>\n<li>\n<h1>Foo</h1>\n</li>\n<li>\n<h2>Bar</h2>\nbaz</li>\n</ul>\n"],
            'Example 301' => ["- foo\n- bar\n+ baz\n", "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<ul>\n<li>baz</li>\n</ul>\n"],
            'Example 302' => ["1. foo\n2. bar\n3) baz\n", "<ol>\n<li>foo</li>\n<li>bar</li>\n</ol>\n<ol start=\"3\">\n<li>baz</li>\n</ol>\n"],
            'Example 303' => ["Foo\n- bar\n- baz\n", "<p>Foo</p>\n<ul>\n<li>bar</li>\n<li>baz</li>\n</ul>\n"],
            'Example 304' => ["The number of windows in my house is\n14.  The number of doors is 6.\n", "<p>The number of windows in my house is\n14.  The number of doors is 6.</p>\n"],
            'Example 305' => ["The number of windows in my house is\n1.  The number of doors is 6.\n", "<p>The number of windows in my house is</p>\n<ol>\n<li>The number of doors is 6.</li>\n</ol>\n"],
            'Example 306' => ["- foo\n\n- bar\n\n\n- baz\n", "<ul>\n<li>\n<p>foo</p>\n</li>\n<li>\n<p>bar</p>\n</li>\n<li>\n<p>baz</p>\n</li>\n</ul>\n"],
            'Example 307' => ["- foo\n  - bar\n    - baz\n\n\n      bim\n", "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>\n<p>baz</p>\n<p>bim</p>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n"],
            'Example 308' => ["- foo\n- bar\n\n<!-- -->\n\n- baz\n- bim\n", "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<!-- -->\n<ul>\n<li>baz</li>\n<li>bim</li>\n</ul>\n"],
            'Example 309' => ["-   foo\n\n    notcode\n\n-   foo\n\n<!-- -->\n\n    code\n", "<ul>\n<li>\n<p>foo</p>\n<p>notcode</p>\n</li>\n<li>\n<p>foo</p>\n</li>\n</ul>\n<!-- -->\n<pre><code>code\n</code></pre>\n"],
            'Example 310' => ["- a\n - b\n  - c\n   - d\n  - e\n - f\n- g\n", "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n<li>e</li>\n<li>f</li>\n<li>g</li>\n</ul>\n"],
            'Example 311' => ["1. a\n\n  2. b\n\n   3. c\n", "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ol>\n"],
            'Example 312' => ["- a\n - b\n  - c\n   - d\n    - e\n", "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d\n- e</li>\n</ul>\n"],
            'Example 313' => ["1. a\n\n  2. b\n\n    3. c\n", "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n</ol>\n<pre><code>3. c\n</code></pre>\n"],
            'Example 314' => ["- a\n- b\n\n- c\n", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ul>\n"],
            'Example 315' => ["* a\n*\n\n* c\n", "<ul>\n<li>\n<p>a</p>\n</li>\n<li></li>\n<li>\n<p>c</p>\n</li>\n</ul>\n"],
            'Example 316' => ["- a\n- b\n\n  c\n- d\n", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n"],
            'Example 317' => ["- a\n- b\n\n  [ref]: /url\n- d\n", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n"],
            'Example 318' => ["- a\n- ```\n  b\n\n\n  ```\n- c\n", "<ul>\n<li>a</li>\n<li>\n<pre><code>b\n\n\n</code></pre>\n</li>\n<li>c</li>\n</ul>\n"],
            'Example 319' => ["- a\n  - b\n\n    c\n- d\n", "<ul>\n<li>a\n<ul>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n</ul>\n</li>\n<li>d</li>\n</ul>\n"],
            'Example 320' => ["* a\n  > b\n  >\n* c\n", "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n</li>\n<li>c</li>\n</ul>\n"],
            'Example 321' => ["- a\n  > b\n  ```\n  c\n  ```\n- d\n", "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n<pre><code>c\n</code></pre>\n</li>\n<li>d</li>\n</ul>\n"],
            'Example 322' => ["- a\n", "<ul>\n<li>a</li>\n</ul>\n"],
            'Example 323' => ["- a\n  - b\n", "<ul>\n<li>a\n<ul>\n<li>b</li>\n</ul>\n</li>\n</ul>\n"],
            'Example 324' => ["1. ```\n   foo\n   ```\n\n   bar\n", "<ol>\n<li>\n<pre><code>foo\n</code></pre>\n<p>bar</p>\n</li>\n</ol>\n"],
            'Example 325' => ["* foo\n  * bar\n\n  baz\n", "<ul>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n<p>baz</p>\n</li>\n</ul>\n"],
            'Example 326' => ["- a\n  - b\n  - c\n\n- d\n  - e\n  - f\n", "<ul>\n<li>\n<p>a</p>\n<ul>\n<li>b</li>\n<li>c</li>\n</ul>\n</li>\n<li>\n<p>d</p>\n<ul>\n<li>e</li>\n<li>f</li>\n</ul>\n</li>\n</ul>\n"],
            'Example 327' => ["`hi`lo`\n", "<p><code>hi</code>lo`</p>\n"],
            'Example 328' => ["`foo`\n", "<p><code>foo</code></p>\n"],
            'Example 329' => ["`` foo ` bar ``\n", "<p><code>foo ` bar</code></p>\n"],
            'Example 330' => ["` `` `\n", "<p><code>``</code></p>\n"],
            'Example 331' => ["`  ``  `\n", "<p><code> `` </code></p>\n"],
            'Example 332' => ["` a`\n", "<p><code> a</code></p>\n"],
            'Example 333' => ["` b `\n", "<p><code> b </code></p>\n"],
            'Example 334' => ["` `\n`  `\n", "<p><code> </code>\n<code>  </code></p>\n"],
            'Example 335' => ["``\nfoo\nbar  \nbaz\n``\n", "<p><code>foo bar   baz</code></p>\n"],
            'Example 336' => ["``\nfoo \n``\n", "<p><code>foo </code></p>\n"],
            'Example 337' => ["`foo   bar \nbaz`\n", "<p><code>foo   bar  baz</code></p>\n"],
            'Example 338' => ["`foo\\`bar`\n", "<p><code>foo\\</code>bar`</p>\n"],
            'Example 339' => ["``foo`bar``\n", "<p><code>foo`bar</code></p>\n"],
            'Example 340' => ["` foo `` bar `\n", "<p><code>foo `` bar</code></p>\n"],
            'Example 341' => ["*foo`*`\n", "<p>*foo<code>*</code></p>\n"],
            'Example 342' => ["[not a `link](/foo`)\n", "<p>[not a <code>link](/foo</code>)</p>\n"],
            'Example 343' => ["`<a href=\"`\">`\n", "<p><code>&lt;a href=&quot;</code>&quot;&gt;`</p>\n"],
            'Example 344' => ["<a href=\"`\">`\n", "<p><a href=\"`\">`</p>\n"],
            'Example 345' => ["`<https://foo.bar.`baz>`\n", "<p><code>&lt;https://foo.bar.</code>baz&gt;`</p>\n"],
            'Example 346' => ["<https://foo.bar.`baz>`\n", "<p><a href=\"https://foo.bar.%60baz\">https://foo.bar.`baz</a>`</p>\n"],
            'Example 347' => ["```foo``\n", "<p>```foo``</p>\n"],
            'Example 348' => ["`foo\n", "<p>`foo</p>\n"],
            'Example 349' => ["`foo``bar``\n", "<p>`foo<code>bar</code></p>\n"],
            'Example 350' => ["*foo bar*\n", "<p><em>foo bar</em></p>\n"],
            'Example 351' => ["a * foo bar*\n", "<p>a * foo bar*</p>\n"],
            'Example 352' => ["a*\"foo\"*\n", "<p>a*&quot;foo&quot;*</p>\n"],
            'Example 353' => ["* a *\n", "<p>* a *</p>\n"],
            'Example 354' => ["*\$*alpha.\n\n*£*bravo.\n\n*€*charlie.\n", "<p>*\$*alpha.</p>\n<p>*£*bravo.</p>\n<p>*€*charlie.</p>\n"],
            'Example 355' => ["foo*bar*\n", "<p>foo<em>bar</em></p>\n"],
            'Example 356' => ["5*6*78\n", "<p>5<em>6</em>78</p>\n"],
            'Example 357' => ["_foo bar_\n", "<p><em>foo bar</em></p>\n"],
            'Example 358' => ["_ foo bar_\n", "<p>_ foo bar_</p>\n"],
            'Example 359' => ["a_\"foo\"_\n", "<p>a_&quot;foo&quot;_</p>\n"],
            'Example 360' => ["foo_bar_\n", "<p>foo_bar_</p>\n"],
            'Example 361' => ["5_6_78\n", "<p>5_6_78</p>\n"],
            'Example 362' => ["пристаням_стремятся_\n", "<p>пристаням_стремятся_</p>\n"],
            'Example 363' => ["aa_\"bb\"_cc\n", "<p>aa_&quot;bb&quot;_cc</p>\n"],
            'Example 364' => ["foo-_(bar)_\n", "<p>foo-<em>(bar)</em></p>\n"],
            'Example 365' => ["_foo*\n", "<p>_foo*</p>\n"],
            'Example 366' => ["*foo bar *\n", "<p>*foo bar *</p>\n"],
            'Example 367' => ["*foo bar\n*\n", "<p>*foo bar\n*</p>\n"],
            'Example 368' => ["*(*foo)\n", "<p>*(*foo)</p>\n"],
            'Example 369' => ["*(*foo*)*\n", "<p><em>(<em>foo</em>)</em></p>\n"],
            'Example 370' => ["*foo*bar\n", "<p><em>foo</em>bar</p>\n"],
            'Example 371' => ["_foo bar _\n", "<p>_foo bar _</p>\n"],
            'Example 372' => ["_(_foo)\n", "<p>_(_foo)</p>\n"],
            'Example 373' => ["_(_foo_)_\n", "<p><em>(<em>foo</em>)</em></p>\n"],
            'Example 374' => ["_foo_bar\n", "<p>_foo_bar</p>\n"],
            'Example 375' => ["_пристаням_стремятся\n", "<p>_пристаням_стремятся</p>\n"],
            'Example 376' => ["_foo_bar_baz_\n", "<p><em>foo_bar_baz</em></p>\n"],
            'Example 377' => ["_(bar)_.\n", "<p><em>(bar)</em>.</p>\n"],
            'Example 378' => ["**foo bar**\n", "<p><strong>foo bar</strong></p>\n"],
            'Example 379' => ["** foo bar**\n", "<p>** foo bar**</p>\n"],
            'Example 380' => ["a**\"foo\"**\n", "<p>a**&quot;foo&quot;**</p>\n"],
            'Example 381' => ["foo**bar**\n", "<p>foo<strong>bar</strong></p>\n"],
            'Example 382' => ["__foo bar__\n", "<p><strong>foo bar</strong></p>\n"],
            'Example 383' => ["__ foo bar__\n", "<p>__ foo bar__</p>\n"],
            'Example 384' => ["__\nfoo bar__\n", "<p>__\nfoo bar__</p>\n"],
            'Example 385' => ["a__\"foo\"__\n", "<p>a__&quot;foo&quot;__</p>\n"],
            'Example 386' => ["foo__bar__\n", "<p>foo__bar__</p>\n"],
            'Example 387' => ["5__6__78\n", "<p>5__6__78</p>\n"],
            'Example 388' => ["пристаням__стремятся__\n", "<p>пристаням__стремятся__</p>\n"],
            'Example 389' => ["__foo, __bar__, baz__\n", "<p><strong>foo, <strong>bar</strong>, baz</strong></p>\n"],
            'Example 390' => ["foo-__(bar)__\n", "<p>foo-<strong>(bar)</strong></p>\n"],
            'Example 391' => ["**foo bar **\n", "<p>**foo bar **</p>\n"],
            'Example 392' => ["**(**foo)\n", "<p>**(**foo)</p>\n"],
            'Example 393' => ["*(**foo**)*\n", "<p><em>(<strong>foo</strong>)</em></p>\n"],
            'Example 394' => ["**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n", "<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>\n"],
            'Example 395' => ["**foo \"*bar*\" foo**\n", "<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>\n"],
            'Example 396' => ["**foo**bar\n", "<p><strong>foo</strong>bar</p>\n"],
            'Example 397' => ["__foo bar __\n", "<p>__foo bar __</p>\n"],
            'Example 398' => ["__(__foo)\n", "<p>__(__foo)</p>\n"],
            'Example 399' => ["_(__foo__)_\n", "<p><em>(<strong>foo</strong>)</em></p>\n"],
            'Example 400' => ["__foo__bar\n", "<p>__foo__bar</p>\n"],
            'Example 401' => ["__пристаням__стремятся\n", "<p>__пристаням__стремятся</p>\n"],
            'Example 402' => ["__foo__bar__baz__\n", "<p><strong>foo__bar__baz</strong></p>\n"],
            'Example 403' => ["__(bar)__.\n", "<p><strong>(bar)</strong>.</p>\n"],
            'Example 404' => ["*foo [bar](/url)*\n", "<p><em>foo <a href=\"/url\">bar</a></em></p>\n"],
            'Example 405' => ["*foo\nbar*\n", "<p><em>foo\nbar</em></p>\n"],
            'Example 406' => ["_foo __bar__ baz_\n", "<p><em>foo <strong>bar</strong> baz</em></p>\n"],
            'Example 407' => ["_foo _bar_ baz_\n", "<p><em>foo <em>bar</em> baz</em></p>\n"],
            'Example 408' => ["__foo_ bar_\n", "<p><em><em>foo</em> bar</em></p>\n"],
            'Example 409' => ["*foo *bar**\n", "<p><em>foo <em>bar</em></em></p>\n"],
            'Example 410' => ["*foo **bar** baz*\n", "<p><em>foo <strong>bar</strong> baz</em></p>\n"],
            'Example 411' => ["*foo**bar**baz*\n", "<p><em>foo<strong>bar</strong>baz</em></p>\n"],
            'Example 412' => ["*foo**bar*\n", "<p><em>foo**bar</em></p>\n"],
            'Example 413' => ["***foo** bar*\n", "<p><em><strong>foo</strong> bar</em></p>\n"],
            'Example 414' => ["*foo **bar***\n", "<p><em>foo <strong>bar</strong></em></p>\n"],
            'Example 415' => ["*foo**bar***\n", "<p><em>foo<strong>bar</strong></em></p>\n"],
            'Example 416' => ["foo***bar***baz\n", "<p>foo<em><strong>bar</strong></em>baz</p>\n"],
            'Example 417' => ["foo******bar*********baz\n", "<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>\n"],
            'Example 418' => ["*foo **bar *baz* bim** bop*\n", "<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>\n"],
            'Example 419' => ["*foo [*bar*](/url)*\n", "<p><em>foo <a href=\"/url\"><em>bar</em></a></em></p>\n"],
            'Example 420' => ["** is not an empty emphasis\n", "<p>** is not an empty emphasis</p>\n"],
            'Example 421' => ["**** is not an empty strong emphasis\n", "<p>**** is not an empty strong emphasis</p>\n"],
            'Example 422' => ["**foo [bar](/url)**\n", "<p><strong>foo <a href=\"/url\">bar</a></strong></p>\n"],
            'Example 423' => ["**foo\nbar**\n", "<p><strong>foo\nbar</strong></p>\n"],
            'Example 424' => ["__foo _bar_ baz__\n", "<p><strong>foo <em>bar</em> baz</strong></p>\n"],
            'Example 425' => ["__foo __bar__ baz__\n", "<p><strong>foo <strong>bar</strong> baz</strong></p>\n"],
            'Example 426' => ["____foo__ bar__\n", "<p><strong><strong>foo</strong> bar</strong></p>\n"],
            'Example 427' => ["**foo **bar****\n", "<p><strong>foo <strong>bar</strong></strong></p>\n"],
            'Example 428' => ["**foo *bar* baz**\n", "<p><strong>foo <em>bar</em> baz</strong></p>\n"],
            'Example 429' => ["**foo*bar*baz**\n", "<p><strong>foo<em>bar</em>baz</strong></p>\n"],
            'Example 430' => ["***foo* bar**\n", "<p><strong><em>foo</em> bar</strong></p>\n"],
            'Example 431' => ["**foo *bar***\n", "<p><strong>foo <em>bar</em></strong></p>\n"],
            'Example 432' => ["**foo *bar **baz**\nbim* bop**\n", "<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>\n"],
            'Example 433' => ["**foo [*bar*](/url)**\n", "<p><strong>foo <a href=\"/url\"><em>bar</em></a></strong></p>\n"],
            'Example 434' => ["__ is not an empty emphasis\n", "<p>__ is not an empty emphasis</p>\n"],
            'Example 435' => ["____ is not an empty strong emphasis\n", "<p>____ is not an empty strong emphasis</p>\n"],
            'Example 436' => ["foo ***\n", "<p>foo ***</p>\n"],
            'Example 437' => ["foo *\\**\n", "<p>foo <em>*</em></p>\n"],
            'Example 438' => ["foo *_*\n", "<p>foo <em>_</em></p>\n"],
            'Example 439' => ["foo *****\n", "<p>foo *****</p>\n"],
            'Example 440' => ["foo **\\***\n", "<p>foo <strong>*</strong></p>\n"],
            'Example 441' => ["foo **_**\n", "<p>foo <strong>_</strong></p>\n"],
            'Example 442' => ["**foo*\n", "<p>*<em>foo</em></p>\n"],
            'Example 443' => ["*foo**\n", "<p><em>foo</em>*</p>\n"],
            'Example 444' => ["***foo**\n", "<p>*<strong>foo</strong></p>\n"],
            'Example 445' => ["****foo*\n", "<p>***<em>foo</em></p>\n"],
            'Example 446' => ["**foo***\n", "<p><strong>foo</strong>*</p>\n"],
            'Example 447' => ["*foo****\n", "<p><em>foo</em>***</p>\n"],
            'Example 448' => ["foo ___\n", "<p>foo ___</p>\n"],
            'Example 449' => ["foo _\\__\n", "<p>foo <em>_</em></p>\n"],
            'Example 450' => ["foo _*_\n", "<p>foo <em>*</em></p>\n"],
            'Example 451' => ["foo _____\n", "<p>foo _____</p>\n"],
            'Example 452' => ["foo __\\___\n", "<p>foo <strong>_</strong></p>\n"],
            'Example 453' => ["foo __*__\n", "<p>foo <strong>*</strong></p>\n"],
            'Example 454' => ["__foo_\n", "<p>_<em>foo</em></p>\n"],
            'Example 455' => ["_foo__\n", "<p><em>foo</em>_</p>\n"],
            'Example 456' => ["___foo__\n", "<p>_<strong>foo</strong></p>\n"],
            'Example 457' => ["____foo_\n", "<p>___<em>foo</em></p>\n"],
            'Example 458' => ["__foo___\n", "<p><strong>foo</strong>_</p>\n"],
            'Example 459' => ["_foo____\n", "<p><em>foo</em>___</p>\n"],
            'Example 460' => ["**foo**\n", "<p><strong>foo</strong></p>\n"],
            'Example 461' => ["*_foo_*\n", "<p><em><em>foo</em></em></p>\n"],
            'Example 462' => ["__foo__\n", "<p><strong>foo</strong></p>\n"],
            'Example 463' => ["_*foo*_\n", "<p><em><em>foo</em></em></p>\n"],
            'Example 464' => ["****foo****\n", "<p><strong><strong>foo</strong></strong></p>\n"],
            'Example 465' => ["____foo____\n", "<p><strong><strong>foo</strong></strong></p>\n"],
            'Example 466' => ["******foo******\n", "<p><strong><strong><strong>foo</strong></strong></strong></p>\n"],
            'Example 467' => ["***foo***\n", "<p><em><strong>foo</strong></em></p>\n"],
            'Example 468' => ["_____foo_____\n", "<p><em><strong><strong>foo</strong></strong></em></p>\n"],
            'Example 469' => ["*foo _bar* baz_\n", "<p><em>foo _bar</em> baz_</p>\n"],
            'Example 470' => ["*foo __bar *baz bim__ bam*\n", "<p><em>foo <strong>bar *baz bim</strong> bam</em></p>\n"],
            'Example 471' => ["**foo **bar baz**\n", "<p>**foo <strong>bar baz</strong></p>\n"],
            'Example 472' => ["*foo *bar baz*\n", "<p>*foo <em>bar baz</em></p>\n"],
            'Example 473' => ["*[bar*](/url)\n", "<p>*<a href=\"/url\">bar*</a></p>\n"],
            'Example 474' => ["_foo [bar_](/url)\n", "<p>_foo <a href=\"/url\">bar_</a></p>\n"],
            'Example 475' => ["*<img src=\"foo\" title=\"*\"/>\n", "<p>*<img src=\"foo\" title=\"*\"/></p>\n"],
            'Example 476' => ["**<a href=\"**\">\n", "<p>**<a href=\"**\"></p>\n"],
            'Example 477' => ["__<a href=\"__\">\n", "<p>__<a href=\"__\"></p>\n"],
            'Example 478' => ["*a `*`*\n", "<p><em>a <code>*</code></em></p>\n"],
            'Example 479' => ["_a `_`_\n", "<p><em>a <code>_</code></em></p>\n"],
            'Example 480' => ["**a<https://foo.bar/?q=**>\n", "<p>**a<a href=\"https://foo.bar/?q=**\">https://foo.bar/?q=**</a></p>\n"],
            'Example 481' => ["__a<https://foo.bar/?q=__>\n", "<p>__a<a href=\"https://foo.bar/?q=__\">https://foo.bar/?q=__</a></p>\n"],
            'Example 482' => ["[link](/uri \"title\")\n", "<p><a href=\"/uri\" title=\"title\">link</a></p>\n"],
            'Example 483' => ["[link](/uri)\n", "<p><a href=\"/uri\">link</a></p>\n"],
            'Example 484' => ["[](./target.md)\n", "<p><a href=\"./target.md\"></a></p>\n"],
            'Example 485' => ["[link]()\n", "<p><a href=\"\">link</a></p>\n"],
            'Example 486' => ["[link](<>)\n", "<p><a href=\"\">link</a></p>\n"],
            'Example 487' => ["[]()\n", "<p><a href=\"\"></a></p>\n"],
            'Example 488' => ["[link](/my uri)\n", "<p>[link](/my uri)</p>\n"],
            'Example 489' => ["[link](</my uri>)\n", "<p><a href=\"/my%20uri\">link</a></p>\n"],
            'Example 490' => ["[link](foo\nbar)\n", "<p>[link](foo\nbar)</p>\n"],
            'Example 491' => ["[link](<foo\nbar>)\n", "<p>[link](<foo\nbar>)</p>\n"],
            'Example 492' => ["[a](<b)c>)\n", "<p><a href=\"b)c\">a</a></p>\n"],
            'Example 493' => ["[link](<foo\\>)\n", "<p>[link](&lt;foo&gt;)</p>\n"],
            'Example 494' => ["[a](<b)c\n[a](<b)c>\n[a](<b>c)\n", "<p>[a](&lt;b)c\n[a](&lt;b)c&gt;\n[a](<b>c)</p>\n"],
            'Example 495' => ["[link](\\(foo\\))\n", "<p><a href=\"(foo)\">link</a></p>\n"],
            'Example 496' => ["[link](foo(and(bar)))\n", "<p><a href=\"foo(and(bar))\">link</a></p>\n"],
            'Example 497' => ["[link](foo(and(bar))\n", "<p>[link](foo(and(bar))</p>\n"],
            'Example 498' => ["[link](foo\\(and\\(bar\\))\n", "<p><a href=\"foo(and(bar)\">link</a></p>\n"],
            'Example 499' => ["[link](<foo(and(bar)>)\n", "<p><a href=\"foo(and(bar)\">link</a></p>\n"],
            'Example 500' => ["[link](foo\\)\\:)\n", "<p><a href=\"foo):\">link</a></p>\n"],
            'Example 501' => ["[link](#fragment)\n\n[link](https://example.com#fragment)\n\n[link](https://example.com?foo=3#frag)\n", "<p><a href=\"#fragment\">link</a></p>\n<p><a href=\"https://example.com#fragment\">link</a></p>\n<p><a href=\"https://example.com?foo=3#frag\">link</a></p>\n"],
            'Example 502' => ["[link](foo\\bar)\n", "<p><a href=\"foo%5Cbar\">link</a></p>\n"],
            'Example 503' => ["[link](foo%20b&auml;)\n", "<p><a href=\"foo%20b%C3%A4\">link</a></p>\n"],
            'Example 504' => ["[link](\"title\")\n", "<p><a href=\"%22title%22\">link</a></p>\n"],
            'Example 505' => ["[link](/url \"title\")\n[link](/url 'title')\n[link](/url (title))\n", "<p><a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a></p>\n"],
            'Example 506' => ["[link](/url \"title \\\"&quot;\")\n", "<p><a href=\"/url\" title=\"title &quot;&quot;\">link</a></p>\n"],
            'Example 507' => ["[link](/url \"title\")\n", "<p><a href=\"/url%C2%A0%22title%22\">link</a></p>\n"],
            'Example 508' => ["[link](/url \"title \"and\" title\")\n", "<p>[link](/url &quot;title &quot;and&quot; title&quot;)</p>\n"],
            'Example 509' => ["[link](/url 'title \"and\" title')\n", "<p><a href=\"/url\" title=\"title &quot;and&quot; title\">link</a></p>\n"],
            'Example 510' => ["[link](   /uri\n  \"title\"  )\n", "<p><a href=\"/uri\" title=\"title\">link</a></p>\n"],
            'Example 511' => ["[link] (/uri)\n", "<p>[link] (/uri)</p>\n"],
            'Example 512' => ["[link [foo [bar]]](/uri)\n", "<p><a href=\"/uri\">link [foo [bar]]</a></p>\n"],
            'Example 513' => ["[link] bar](/uri)\n", "<p>[link] bar](/uri)</p>\n"],
            'Example 514' => ["[link [bar](/uri)\n", "<p>[link <a href=\"/uri\">bar</a></p>\n"],
            'Example 515' => ["[link \\[bar](/uri)\n", "<p><a href=\"/uri\">link [bar</a></p>\n"],
            'Example 516' => ["[link *foo **bar** `#`*](/uri)\n", "<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n"],
            'Example 517' => ["[![moon](moon.jpg)](/uri)\n", "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>\n"],
            'Example 518' => ["[foo [bar](/uri)](/uri)\n", "<p>[foo <a href=\"/uri\">bar</a>](/uri)</p>\n"],
            'Example 519' => ["[foo *[bar [baz](/uri)](/uri)*](/uri)\n", "<p>[foo <em>[bar <a href=\"/uri\">baz</a>](/uri)</em>](/uri)</p>\n"],
            'Example 520' => ["![[[foo](uri1)](uri2)](uri3)\n", "<p><img src=\"uri3\" alt=\"[foo](uri2)\" /></p>\n"],
            'Example 521' => ["*[foo*](/uri)\n", "<p>*<a href=\"/uri\">foo*</a></p>\n"],
            'Example 522' => ["[foo *bar](baz*)\n", "<p><a href=\"baz*\">foo *bar</a></p>\n"],
            'Example 523' => ["*foo [bar* baz]\n", "<p><em>foo [bar</em> baz]</p>\n"],
            'Example 524' => ["[foo <bar attr=\"](baz)\">\n", "<p>[foo <bar attr=\"](baz)\"></p>\n"],
            'Example 525' => ["[foo`](/uri)`\n", "<p>[foo<code>](/uri)</code></p>\n"],
            'Example 526' => ["[foo<https://example.com/?search=](uri)>\n", "<p>[foo<a href=\"https://example.com/?search=%5D(uri)\">https://example.com/?search=](uri)</a></p>\n"],
            'Example 527' => ["[foo][bar]\n\n[bar]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"],
            'Example 528' => ["[link [foo [bar]]][ref]\n\n[ref]: /uri\n", "<p><a href=\"/uri\">link [foo [bar]]</a></p>\n"],
            'Example 529' => ["[link \\[bar][ref]\n\n[ref]: /uri\n", "<p><a href=\"/uri\">link [bar</a></p>\n"],
            'Example 530' => ["[link *foo **bar** `#`*][ref]\n\n[ref]: /uri\n", "<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n"],
            'Example 531' => ["[![moon](moon.jpg)][ref]\n\n[ref]: /uri\n", "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>\n"],
            'Example 532' => ["[foo [bar](/uri)][ref]\n\n[ref]: /uri\n", "<p>[foo <a href=\"/uri\">bar</a>]<a href=\"/uri\">ref</a></p>\n"],
            'Example 533' => ["[foo *bar [baz][ref]*][ref]\n\n[ref]: /uri\n", "<p>[foo <em>bar <a href=\"/uri\">baz</a></em>]<a href=\"/uri\">ref</a></p>\n"],
            'Example 534' => ["*[foo*][ref]\n\n[ref]: /uri\n", "<p>*<a href=\"/uri\">foo*</a></p>\n"],
            'Example 535' => ["[foo *bar][ref]*\n\n[ref]: /uri\n", "<p><a href=\"/uri\">foo *bar</a>*</p>\n"],
            'Example 536' => ["[foo <bar attr=\"][ref]\">\n\n[ref]: /uri\n", "<p>[foo <bar attr=\"][ref]\"></p>\n"],
            'Example 537' => ["[foo`][ref]`\n\n[ref]: /uri\n", "<p>[foo<code>][ref]</code></p>\n"],
            'Example 538' => ["[foo<https://example.com/?search=][ref]>\n\n[ref]: /uri\n", "<p>[foo<a href=\"https://example.com/?search=%5D%5Bref%5D\">https://example.com/?search=][ref]</a></p>\n"],
            'Example 539' => ["[foo][BaR]\n\n[bar]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"],
            'Example 540' => ["[ẞ]\n\n[SS]: /url\n", "<p><a href=\"/url\">ẞ</a></p>\n"],
            'Example 541' => ["[Foo\n  bar]: /url\n\n[Baz][Foo bar]\n", "<p><a href=\"/url\">Baz</a></p>\n"],
            'Example 542' => ["[foo] [bar]\n\n[bar]: /url \"title\"\n", "<p>[foo] <a href=\"/url\" title=\"title\">bar</a></p>\n"],
            'Example 543' => ["[foo]\n[bar]\n\n[bar]: /url \"title\"\n", "<p>[foo]\n<a href=\"/url\" title=\"title\">bar</a></p>\n"],
            'Example 544' => ["[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]\n", "<p><a href=\"/url1\">bar</a></p>\n"],
            'Example 545' => ["[bar][foo\\!]\n\n[foo!]: /url\n", "<p>[bar][foo!]</p>\n"],
            'Example 546' => ["[foo][ref[]\n\n[ref[]: /uri\n", "<p>[foo][ref[]</p>\n<p>[ref[]: /uri</p>\n"],
            'Example 547' => ["[foo][ref[bar]]\n\n[ref[bar]]: /uri\n", "<p>[foo][ref[bar]]</p>\n<p>[ref[bar]]: /uri</p>\n"],
            'Example 548' => ["[[[foo]]]\n\n[[[foo]]]: /url\n", "<p>[[[foo]]]</p>\n<p>[[[foo]]]: /url</p>\n"],
            'Example 549' => ["[foo][ref\\[]\n\n[ref\\[]: /uri\n", "<p><a href=\"/uri\">foo</a></p>\n"],
            'Example 550' => ["[bar\\\\]: /uri\n\n[bar\\\\]\n", "<p><a href=\"/uri\">bar\\</a></p>\n"],
            'Example 551' => ["[]\n\n[]: /uri\n", "<p>[]</p>\n<p>[]: /uri</p>\n"],
            'Example 552' => ["[\n ]\n\n[\n ]: /uri\n", "<p>[\n]</p>\n<p>[\n]: /uri</p>\n"],
            'Example 553' => ["[foo][]\n\n[foo]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"],
            'Example 554' => ["[*foo* bar][]\n\n[*foo* bar]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>\n"],
            'Example 555' => ["[Foo][]\n\n[foo]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">Foo</a></p>\n"],
            'Example 556' => ["[foo] \n[]\n\n[foo]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">foo</a>\n[]</p>\n"],
            'Example 557' => ["[foo]\n\n[foo]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"],
            'Example 558' => ["[*foo* bar]\n\n[*foo* bar]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>\n"],
            'Example 559' => ["[[*foo* bar]]\n\n[*foo* bar]: /url \"title\"\n", "<p>[<a href=\"/url\" title=\"title\"><em>foo</em> bar</a>]</p>\n"],
            'Example 560' => ["[[bar [foo]\n\n[foo]: /url\n", "<p>[[bar <a href=\"/url\">foo</a></p>\n"],
            'Example 561' => ["[Foo]\n\n[foo]: /url \"title\"\n", "<p><a href=\"/url\" title=\"title\">Foo</a></p>\n"],
            'Example 562' => ["[foo] bar\n\n[foo]: /url\n", "<p><a href=\"/url\">foo</a> bar</p>\n"],
            'Example 563' => ["\\[foo]\n\n[foo]: /url \"title\"\n", "<p>[foo]</p>\n"],
            'Example 564' => ["[foo*]: /url\n\n*[foo*]\n", "<p>*<a href=\"/url\">foo*</a></p>\n"],
            'Example 565' => ["[foo][bar]\n\n[foo]: /url1\n[bar]: /url2\n", "<p><a href=\"/url2\">foo</a></p>\n"],
            'Example 566' => ["[foo][]\n\n[foo]: /url1\n", "<p><a href=\"/url1\">foo</a></p>\n"],
            'Example 567' => ["[foo]()\n\n[foo]: /url1\n", "<p><a href=\"\">foo</a></p>\n"],
            'Example 568' => ["[foo](not a link)\n\n[foo]: /url1\n", "<p><a href=\"/url1\">foo</a>(not a link)</p>\n"],
            'Example 569' => ["[foo][bar][baz]\n\n[baz]: /url\n", "<p>[foo]<a href=\"/url\">bar</a></p>\n"],
            'Example 570' => ["[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2\n", "<p><a href=\"/url2\">foo</a><a href=\"/url1\">baz</a></p>\n"],
            'Example 571' => ["[foo][bar][baz]\n\n[baz]: /url1\n[foo]: /url2\n", "<p>[foo]<a href=\"/url1\">bar</a></p>\n"],
            'Example 572' => ["![foo](/url \"title\")\n", "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"],
            'Example 573' => ["![foo *bar*]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n", "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n"],
            'Example 574' => ["![foo ![bar](/url)](/url2)\n", "<p><img src=\"/url2\" alt=\"foo bar\" /></p>\n"],
            'Example 575' => ["![foo [bar](/url)](/url2)\n", "<p><img src=\"/url2\" alt=\"foo bar\" /></p>\n"],
            'Example 576' => ["![foo *bar*][]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n", "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n"],
            'Example 577' => ["![foo *bar*][foobar]\n\n[FOOBAR]: train.jpg \"train & tracks\"\n", "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n"],
            'Example 578' => ["![foo](train.jpg)\n", "<p><img src=\"train.jpg\" alt=\"foo\" /></p>\n"],
            'Example 579' => ["My ![foo bar](/path/to/train.jpg  \"title\"   )\n", "<p>My <img src=\"/path/to/train.jpg\" alt=\"foo bar\" title=\"title\" /></p>\n"],
            'Example 580' => ["![foo](<url>)\n", "<p><img src=\"url\" alt=\"foo\" /></p>\n"],
            'Example 581' => ["![](/url)\n", "<p><img src=\"/url\" alt=\"\" /></p>\n"],
            'Example 582' => ["![foo][bar]\n\n[bar]: /url\n", "<p><img src=\"/url\" alt=\"foo\" /></p>\n"],
            'Example 583' => ["![foo][bar]\n\n[BAR]: /url\n", "<p><img src=\"/url\" alt=\"foo\" /></p>\n"],
            'Example 584' => ["![foo][]\n\n[foo]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"],
            'Example 585' => ["![*foo* bar][]\n\n[*foo* bar]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"foo bar\" title=\"title\" /></p>\n"],
            'Example 586' => ["![Foo][]\n\n[foo]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"Foo\" title=\"title\" /></p>\n"],
            'Example 587' => ["![foo] \n[]\n\n[foo]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"foo\" title=\"title\" />\n[]</p>\n"],
            'Example 588' => ["![foo]\n\n[foo]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"],
            'Example 589' => ["![*foo* bar]\n\n[*foo* bar]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"foo bar\" title=\"title\" /></p>\n"],
            'Example 590' => ["![[foo]]\n\n[[foo]]: /url \"title\"\n", "<p>![[foo]]</p>\n<p>[[foo]]: /url &quot;title&quot;</p>\n"],
            'Example 591' => ["![Foo]\n\n[foo]: /url \"title\"\n", "<p><img src=\"/url\" alt=\"Foo\" title=\"title\" /></p>\n"],
            'Example 592' => ["!\\[foo]\n\n[foo]: /url \"title\"\n", "<p>![foo]</p>\n"],
            'Example 593' => ["\\![foo]\n\n[foo]: /url \"title\"\n", "<p>!<a href=\"/url\" title=\"title\">foo</a></p>\n"],
            'Example 594' => ["<http://foo.bar.baz>\n", "<p><a href=\"http://foo.bar.baz\">http://foo.bar.baz</a></p>\n"],
            'Example 595' => ["<https://foo.bar.baz/test?q=hello&id=22&boolean>\n", "<p><a href=\"https://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean\">https://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>\n"],
            'Example 596' => ["<irc://foo.bar:2233/baz>\n", "<p><a href=\"irc://foo.bar:2233/baz\">irc://foo.bar:2233/baz</a></p>\n"],
            'Example 597' => ["<MAILTO:FOO@BAR.BAZ>\n", "<p><a href=\"MAILTO:FOO@BAR.BAZ\">MAILTO:FOO@BAR.BAZ</a></p>\n"],
            'Example 598' => ["<a+b+c:d>\n", "<p><a href=\"a+b+c:d\">a+b+c:d</a></p>\n"],
            'Example 599' => ["<made-up-scheme://foo,bar>\n", "<p><a href=\"made-up-scheme://foo,bar\">made-up-scheme://foo,bar</a></p>\n"],
            'Example 600' => ["<https://../>\n", "<p><a href=\"https://../\">https://../</a></p>\n"],
            'Example 601' => ["<localhost:5001/foo>\n", "<p><a href=\"localhost:5001/foo\">localhost:5001/foo</a></p>\n"],
            'Example 602' => ["<https://foo.bar/baz bim>\n", "<p>&lt;https://foo.bar/baz bim&gt;</p>\n"],
            'Example 603' => ["<https://example.com/\\[\\>\n", "<p><a href=\"https://example.com/%5C%5B%5C\">https://example.com/\\[\\</a></p>\n"],
            'Example 604' => ["<foo@bar.example.com>\n", "<p><a href=\"mailto:foo@bar.example.com\">foo@bar.example.com</a></p>\n"],
            'Example 605' => ["<foo+special@Bar.baz-bar0.com>\n", "<p><a href=\"mailto:foo+special@Bar.baz-bar0.com\">foo+special@Bar.baz-bar0.com</a></p>\n"],
            'Example 606' => ["<foo\\+@bar.example.com>\n", "<p>&lt;foo+@bar.example.com&gt;</p>\n"],
            'Example 607' => ["<>\n", "<p>&lt;&gt;</p>\n"],
            'Example 608' => ["< https://foo.bar >\n", "<p>&lt; https://foo.bar &gt;</p>\n"],
            'Example 609' => ["<m:abc>\n", "<p>&lt;m:abc&gt;</p>\n"],
            'Example 610' => ["<foo.bar.baz>\n", "<p>&lt;foo.bar.baz&gt;</p>\n"],
            'Example 611' => ["https://example.com\n", "<p>https://example.com</p>\n"],
            'Example 612' => ["foo@bar.example.com\n", "<p>foo@bar.example.com</p>\n"],
            'Example 613' => ["<a><bab><c2c>\n", "<p><a><bab><c2c></p>\n"],
            'Example 614' => ["<a/><b2/>\n", "<p><a/><b2/></p>\n"],
            'Example 615' => ["<a  /><b2\ndata=\"foo\" >\n", "<p><a  /><b2\ndata=\"foo\" ></p>\n"],
            'Example 616' => ["<a foo=\"bar\" bam = 'baz <em>\"</em>'\n_boolean zoop:33=zoop:33 />\n", "<p><a foo=\"bar\" bam = 'baz <em>\"</em>'\n_boolean zoop:33=zoop:33 /></p>\n"],
            'Example 617' => ["Foo <responsive-image src=\"foo.jpg\" />\n", "<p>Foo <responsive-image src=\"foo.jpg\" /></p>\n"],
            'Example 618' => ["<33> <__>\n", "<p>&lt;33&gt; &lt;__&gt;</p>\n"],
            'Example 619' => ["<a h*#ref=\"hi\">\n", "<p>&lt;a h*#ref=&quot;hi&quot;&gt;</p>\n"],
            'Example 620' => ["<a href=\"hi'> <a href=hi'>\n", "<p>&lt;a href=&quot;hi'&gt; &lt;a href=hi'&gt;</p>\n"],
            'Example 621' => ["< a><\nfoo><bar/ >\n<foo bar=baz\nbim!bop />\n", "<p>&lt; a&gt;&lt;\nfoo&gt;&lt;bar/ &gt;\n&lt;foo bar=baz\nbim!bop /&gt;</p>\n"],
            'Example 622' => ["<a href='bar'title=title>\n", "<p>&lt;a href='bar'title=title&gt;</p>\n"],
            'Example 623' => ["</a></foo >\n", "<p></a></foo ></p>\n"],
            'Example 624' => ["</a href=\"foo\">\n", "<p>&lt;/a href=&quot;foo&quot;&gt;</p>\n"],
            'Example 625' => ["foo <!-- this is a --\ncomment - with hyphens -->\n", "<p>foo <!-- this is a --\ncomment - with hyphens --></p>\n"],
            'Example 626' => ["foo <!--> foo -->\n\nfoo <!---> foo -->\n", "<p>foo <!--> foo --&gt;</p>\n<p>foo <!---> foo --&gt;</p>\n"],
            'Example 627' => ["foo <?php echo \$a; ?>\n", "<p>foo <?php echo \$a; ?></p>\n"],
            'Example 628' => ["foo <!ELEMENT br EMPTY>\n", "<p>foo <!ELEMENT br EMPTY></p>\n"],
            'Example 629' => ["foo <![CDATA[>&<]]>\n", "<p>foo <![CDATA[>&<]]></p>\n"],
            'Example 630' => ["foo <a href=\"&ouml;\">\n", "<p>foo <a href=\"&ouml;\"></p>\n"],
            'Example 631' => ["foo <a href=\"\\*\">\n", "<p>foo <a href=\"\\*\"></p>\n"],
            'Example 632' => ["<a href=\"\\\"\">\n", "<p>&lt;a href=&quot;&quot;&quot;&gt;</p>\n"],
            'Example 633' => ["foo  \nbaz\n", "<p>foo<br />\nbaz</p>\n"],
            'Example 634' => ["foo\\\nbaz\n", "<p>foo<br />\nbaz</p>\n"],
            'Example 635' => ["foo       \nbaz\n", "<p>foo<br />\nbaz</p>\n"],
            'Example 636' => ["foo  \n     bar\n", "<p>foo<br />\nbar</p>\n"],
            'Example 637' => ["foo\\\n     bar\n", "<p>foo<br />\nbar</p>\n"],
            'Example 638' => ["*foo  \nbar*\n", "<p><em>foo<br />\nbar</em></p>\n"],
            'Example 639' => ["*foo\\\nbar*\n", "<p><em>foo<br />\nbar</em></p>\n"],
            'Example 640' => ["`code  \nspan`\n", "<p><code>code   span</code></p>\n"],
            'Example 641' => ["`code\\\nspan`\n", "<p><code>code\\ span</code></p>\n"],
            'Example 642' => ["<a href=\"foo  \nbar\">\n", "<p><a href=\"foo  \nbar\"></p>\n"],
            'Example 643' => ["<a href=\"foo\\\nbar\">\n", "<p><a href=\"foo\\\nbar\"></p>\n"],
            'Example 644' => ["foo\\\n", "<p>foo\\</p>\n"],
            'Example 645' => ["foo  \n", "<p>foo</p>\n"],
            'Example 646' => ["### foo\\\n", "<h3>foo\\</h3>\n"],
            'Example 647' => ["### foo  \n", "<h3>foo</h3>\n"],
            'Example 648' => ["foo\nbaz\n", "<p>foo\nbaz</p>\n"],
            'Example 649' => ["foo \n baz\n", "<p>foo\nbaz</p>\n"],
            'Example 650' => ["hello \$.;'there\n", "<p>hello \$.;'there</p>\n"],
            'Example 651' => ["Foo χρῆν\n", "<p>Foo χρῆν</p>\n"],
            'Example 652' => ["Multiple     spaces\n", "<p>Multiple     spaces</p>\n"],
        ];
    }
}
